### ISSUE TITLE
Black Screen when I start MMM

### ISSUE THREAD

**Issue by BookOfRa** [prasanthsasikumar/MMM-Temperature-Humidity#1]
Hi, I'm more or less new to the Magic Mirror World. I succesfully installed Michi's Basic version of Magic Mirror and designed it for my own needs Now I want to add some more modules and I wanted to start with yours since I had a DHT11 Sensor in spare.
I followed your instructions but when I try to start the program I get stuck on a black screen.

I connected the sensor to GPIO 4 (Pin 7 on Pi3) and I added following lines to config.js:

{
			module: 'MMM-Temperature-Humidity',
			position: 'top_right',
			config: {
				refreshInterval: '50000',
    				temperaturePrefix: 'Room temperature: ',
    				temperatureSuffix: '°C',
    				humidityPrefix: 'Humidity: ',
    				humiditySuffix: '%'
			}
		},

I also changed the Pin from 2 to 7 in nodehelper.....

any ideas what I'm doing wrong?!

Greetings

**Comment by yawnsde** [comment]
Did you run `npm install` in the `MMM-Temperature-Humidity` folder?
If you run `npm start dev` or `node serveronly´, do you see any error messages in console?

**Comment by nitrogen73** [comment]
im too facing the same problem

**Comment by nitrogen73** [comment]
> magicmirror@2.2.2 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.2.2
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
Initializing new module helper ...
Module helper loaded: MMM-GoogleAssistant
No helper found for module: currentweather.
Initializing new module helper ...
Module helper loaded: MMM-awesome-alexa
No helper found for module: weatherforecast.
WARNING! Could not load config file. Starting with default configuration. Error found: Error: Module version mismatch. Expected 50, got 49.
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
Initializing new module helper ...
Module helper loaded: MMM-GoogleAssistant
No helper found for module: currentweather.
Initializing new module helper ...
Module helper loaded: MMM-awesome-alexa
No helper found for module: weatherforecast.
App threw an error during load
Error: Module version mismatch. Expected 50, got 49.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (/home/pi/MagicMirror/modules/default/MMM-Temperature-Humidity/node_modules/bindings/bindings.js:81:44)
Whoops! There was an uncaught exception...
Error: Module version mismatch. Expected 50, got 49.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (/home/pi/MagicMirror/modules/default/MMM-Temperature-Humidity/node_modules/bindings/bindings.js:81:44)

**Comment by nitrogen73** [comment]
could anyone help me on this??
pllzzzzzzzzzzzzz
